import java.awt.Image;
import java.util.Random;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ADM_Agentes extends javax.swing.JInternalFrame {

     private DefaultTableModel model;
     private ArrayList<agentes> datos = new ArrayList<>();
    
    public ADM_Agentes() {
        initComponents();
         model=(DefaultTableModel)this.jTable1.getModel();
         txt_ID.setText(String.valueOf(generar_extension()));
        
        this.btn_Agregar.setIcon(setIcono("/imagenes/agregar.png", this.btn_Agregar));
        this.btn_Agregar.setPressedIcon(this.setIconoPresionado("/imagenes/agregar.png", this.btn_Agregar, 5, 5));
        
        this.btn_Cancelar.setIcon(setIcono("/imagenes/cancelar.png", this.btn_Cancelar));
        this.btn_Cancelar.setPressedIcon(this.setIconoPresionado("/imagenes/cancelar.png", this.btn_Cancelar, 5, 5));
        
        this.btn_Eliminar.setIcon(setIcono("/imagenes/eliminar.png", this.btn_Eliminar));
        this.btn_Eliminar.setPressedIcon(this.setIconoPresionado("/imagenes/eliminar.png", this.btn_Eliminar, 5, 5));
        
        this.btn_Modificar.setIcon(setIcono("/imagenes/modificar.png", this.btn_Modificar));
        this.btn_Modificar.setPressedIcon(this.setIconoPresionado("/imagenes/modificar.png", this.btn_Modificar, 5, 5));
        
    } 
    /*DefaultTableModel model;
    ArrayList<agentes> datos = new ArrayList();*/
    
    public ArrayList<agentes> getAgentes() {
        return datos;
    }
    
    public Icon setIcono(String url, JButton boton){
        
        int ancho = boton.getWidth() > 0 ? boton.getWidth() : 49;
        int alto = boton.getHeight() > 0 ? boton.getHeight() : 49;
        
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        
        return icono;
        
    }
    
    public Icon setIconoPresionado(String url, JButton boton, int ancho, int alto){
        
        int width = boton.getWidth() > 0 ? boton.getWidth() - ancho : 44;
        int height = boton.getHeight() > 0 ? boton.getHeight() - alto : 44;
        
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        
        return icono;
        
    }
    
    private void refrescar(ArrayList<agentes>datos){
        
        System.out.println("Refrescando tabla con los datos: " + datos);
        model.setRowCount(0);
        for(int i=0;i<datos.size();i++){
            agentes x=datos.get(i);
            model.addRow(new Object[]{x.ID_Agente,x.nombre,x.departamento, x.llamadas});
        }
    }
    
    public void incrementarLlamadasAgente(int idAgente) {
        for(agentes ag : datos) {
            if(ag.getID_Agente() == idAgente) {
                //System.out.println("Antes de incrementar: " + ag.getLlamadas());
                ag.setLlamadas(ag.getLlamadas() + 1);
                //System.out.println("Después de incrementar: " + ag.getLlamadas());
                refrescar(datos);
                break;
            }
        }
    }
    public void restarLlamadasAgente(int idAgente) {
        for(agentes ag : datos) {
            if(ag.getID_Agente() == idAgente) {
                //System.out.println("Antes de restar: " + ag.getLlamadas());
                ag.setLlamadas(ag.getLlamadas() - 1);
                //System.out.println("Después de restar: " + ag.getLlamadas());
                refrescar(datos);
                break;
            }
        }
    }
    boolean validar(int x){
        for(int i=0; i<datos.size();i++){
            if(datos.get(i).getID_Agente() == x){
                return true;
            }
        }
        return false;
    }
    
    int generar_extension(){
        int x;
        Random random = new Random();
        
        do{
           x = 1000 + random.nextInt(9000);
        }while(validar(x));
        return x;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ID = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        cb_Departamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Cancelar = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txt_ID.setEditable(false);

        cb_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnico", "Cobros", "Ventas", "Atencion al cliente" }));

        jLabel1.setText("Extensión:");

        jLabel2.setText("Nombre del Agente:");

        jLabel3.setText("Departamento: ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Extensión", "Nombre de Agente", "Departamento", "Llamadas"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });

        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Modificar");

        jLabel5.setText("Agregar");

        jLabel6.setText("Cancelar");

        jLabel7.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ID)
                            .addComponent(txt_Nombre)
                            .addComponent(cb_Departamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void limpiar(){
        txt_ID.setText(String.valueOf(generar_extension()));
        txt_Nombre.setText("");
        cb_Departamento.setSelectedIndex(0);
        btn_Agregar.setEnabled(true);
    }
    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        agentes agente = new agentes();
        agente.setID_Agente(Integer.parseInt(txt_ID.getText()));
        agente.setNombre(this.txt_Nombre.getText());
        agente.setDepartamento((String)this.cb_Departamento.getSelectedItem());
        agente.setLlamadas(0);
        
        datos.add(agente);
        refrescar(datos);
        limpiar();
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    public void extraer_Informacion(int x){
        for(agentes ag : datos){
            if(ag.getID_Agente()== x){
               txt_ID.setText(String.valueOf(ag.getID_Agente()));
               txt_Nombre.setText(ag.getNombre());
               cb_Departamento.setSelectedItem(ag.getDepartamento());
               break;
            }
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btn_Agregar.setEnabled(false);
        int x = jTable1.getSelectedRow();
    
            if (x >= 0) {
                int id = (int) model.getValueAt(x, 0);
                extraer_Informacion(id);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        
        try {
        int id = Integer.parseInt(txt_ID.getText().trim());
        
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i).getID_Agente() == id) {
                datos.remove(i);
                break;
            }
        }
        
            refrescar(datos);
            limpiar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        int idBuscar=Integer.parseInt(txt_ID.getText());
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i).getID_Agente() == idBuscar) {
                agentes nuevo = new agentes();
                nuevo.setID_Agente(idBuscar);
                nuevo.setNombre(txt_Nombre.getText());
                nuevo.setDepartamento(cb_Departamento.getSelectedItem().toString());

                datos.set(i, nuevo);
                break;
            }
        }
        refrescar(datos);
        limpiar();
    }//GEN-LAST:event_btn_ModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JComboBox<String> cb_Departamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
